@username = alex
@password = pass
@baseUrl = http://localhost:3000

###
# @name: Bluesky Post
POST {{baseUrl}}/bluesky/post
Authorization: Basic {{btoa(username + ':' + password)}}
Content-Type: application/x-www-form-urlencoded

content={{encodeURIComponent("Hello from the API!\n\nHere\'s a link: https://docs.bsky.app/")}}

###
# @name: Mastodon Post
POST {{baseUrl}}/mastodon/post
Authorization: Basic {{btoa(username + ':' + password)}}
Content-Type: application/x-www-form-urlencoded

content={{encodeURIComponent("Hello from the API!\n\nHere\'s a link: https://docs.joinmastodon.org/api/")}}

###
# @name: Post to Multiple baseUrls
POST {{baseUrl}}/multiple/post
Authorization: Basic {{btoa(username + ':' + password)}}
Content-Type: application/x-www-form-urlencoded

mastodon=1&bluesky=1&content={{encodeURIComponent("Hello from the API!")}}
