package socialpublish.frontend.models

import socialpublish.frontend.components.SelectOption

val LANGUAGE_OPTIONS =
    listOf(
        SelectOption("English", "en"),
        SelectOption("Arabic", "ar"),
        SelectOption("Basque", "eu"),
        SelectOption("Bengali", "bn"),
        SelectOption("Bulgarian", "bg"),
        SelectOption("Catalan", "ca"),
        SelectOption("Chinese", "zh"),
        SelectOption("Croatian", "hr"),
        SelectOption("Czech", "cs"),
        SelectOption("Danish", "da"),
        SelectOption("Dutch", "nl"),
        SelectOption("Estonian", "et"),
        SelectOption("Finnish", "fi"),
        SelectOption("French", "fr"),
        SelectOption("Galician", "gl"),
        SelectOption("German", "de"),
        SelectOption("Greek", "el"),
        SelectOption("Hindi", "hi"),
        SelectOption("Hungarian", "hu"),
        SelectOption("Icelandic", "is"),
        SelectOption("Indonesian", "id"),
        SelectOption("Irish", "ga"),
        SelectOption("Italian", "it"),
        SelectOption("Japanese", "ja"),
        SelectOption("Korean", "ko"),
        SelectOption("Latvian", "lv"),
        SelectOption("Lithuanian", "lt"),
        SelectOption("Maltese", "mt"),
        SelectOption("Norwegian", "no"),
        SelectOption("Polish", "pl"),
        SelectOption("Portuguese", "pt"),
        SelectOption("Punjabi", "pa"),
        SelectOption("Romanian", "ro"),
        SelectOption("Russian", "ru"),
        SelectOption("Serbian", "sr"),
        SelectOption("Slovak", "sk"),
        SelectOption("Slovenian", "sl"),
        SelectOption("Spanish", "es"),
        SelectOption("Swedish", "sv"),
        SelectOption("Thai", "th"),
        SelectOption("Turkish", "tr"),
        SelectOption("Ukrainian", "uk"),
        SelectOption("Vietnamese", "vi"),
    )
